rpms_base={
    'ceph-common',
    'nfs-utils',
    'jq',
    'conntrack-tools',
    'bash-completion',
    'libseccomp',
    'psmisc',
    'rsync',
    'socat',
    'ipset',
    'ipvsadm',
    'haproxy',
    'chrony',
    'iscsi-initiator-utils',
    'iscsi-initiator-utils-iscsiuio',
    'device-mapper',
    'device-mapper-event',
    'lvm2',
    'device-mapper-multipath',
    'kpartx',
    'sshpass'
}


rpms_gpu={
    'dkms',
    'pciutils',
    'cuda-drivers',
    'nvidia-docker',
    'nvidia-docker2',
    'nvidia-container-runtime'
}